version: "3.9"

services:
  psycopg:
      build: .
      container_name: "psycopg"
      command: python /psycopg/main.py 
      volumes:
      - .:/psycopg
      depends_on:
      - postgres_db
  postgres_db:
    image: postgres:15
    container_name: "postgres_db"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: "pgadmin"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres_db

volumes:
  postgres:
  pgadmin:
